# Generated by Django 3.1.3 on 2020-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.TextField(max_length=10, verbose_name='serial')),
                ('number', models.TextField(max_length=10, verbose_name='number')),
                ('release_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='release date')),
                ('expiration_date', models.DateField(db_index=True, verbose_name='expiration date')),
                ('date_of_use', models.DateField(db_index=True, null=True, verbose_name='date of use')),
                ('value', models.PositiveIntegerField(db_index=True, default=0, verbose_name='summa')),
                ('status', models.CharField(choices=[('N', 'no_active'), ('A', 'active'), ('E', 'expired')], default='N', max_length=1, verbose_name='task status')),
            ],
            options={
                'ordering': ['pk'],
                'unique_together': {('serial', 'number')},
            },
        ),
    ]
