# Generated by Django 3.1.3 on 2020-12-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('domain', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_state', models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('error', 'Error'), ('success', 'Success')], default='not_started', max_length=11)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MigrationTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_type', models.CharField(choices=[('aws', 'Aws'), ('azure', 'Azure'), ('vsphere', 'Vsphere'), ('vcloud', 'Vcloud')], default='aws', max_length=7)),
                ('cloud_credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_targets', to='api.credentials')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MountPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_point_name', models.TextField(max_length=100)),
                ('total_size_of_the_volume', models.PositiveIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_string', models.TextField(max_length=50, unique=True)),
                ('credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workloads', to='api.credentials')),
                ('storage', models.ManyToManyField(related_name='workloads', to='api.MountPoint')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.DeleteModel(
            name='BonusCard',
        ),
        migrations.AddField(
            model_name='migrationtarget',
            name='target_vm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_targets', to='api.workload'),
        ),
        migrations.AddField(
            model_name='migration',
            name='migration_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrations', to='api.migrationtarget'),
        ),
        migrations.AddField(
            model_name='migration',
            name='selected_mount_points',
            field=models.ManyToManyField(related_name='migrations', to='api.MountPoint'),
        ),
        migrations.AddField(
            model_name='migration',
            name='source_of_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrations', to='api.workload'),
        ),
    ]
