# Generated by Django 3.1.3 on 2020-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201212_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='ip_string',
            field=models.TextField(max_length=50),
        ),
    ]
