# Generated by Django 3.1.3 on 2020-12-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201212_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workload',
            old_name='ip_string',
            new_name='ip',
        ),
    ]
